# .github/workflows/manual-check.yml
name: Manual Product Check

on:
  workflow_dispatch:  # Solo attivazione manuale
    inputs:
      check_type:
        description: 'Tipo di controllo'
        required: true
        default: 'check_all'
        type: choice
        options:
        - check_all
        - list_products
        - health_check

jobs:
  check-products:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot[job-queue]==20.8
        pip install requests==2.31.0
        pip install beautifulsoup4==4.12.3
        pip install python-dotenv==1.0.1
        pip install APScheduler>=3.6.3
    
    - name: Create products.json if not exists
      run: |
        if [ ! -f products.json ]; then
          echo "[]" > products.json
        fi
    
    - name: Run manual check
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        CHECK_TYPE: ${{ github.event.inputs.check_type }}
      run: |
        python manual_check_script.py
    
    - name: Save updated products
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update products data'
        file_pattern: 'products.json'
      if: success()
